import { db, clients, tenants, reports } from "@agency/db";
import { eq } from "drizzle-orm";
import { scheduleReportGeneration } from "../lib/queue";

async function generateMonthlyReports() {
  try {
    const [tenant] = await db.select().from(tenants).limit(1);
    if (!tenant?.autoReportEnabled) return;

    const today = new Date();
    if (today.getDate() !== (tenant.autoReportDay ?? 1)) return;

    const prevMonth = today.getMonth() === 0 ? 12 : today.getMonth();
    const year = today.getMonth() === 0 ? today.getFullYear() - 1 : today.getFullYear();

    const activeClients = await db
      .select({ id: clients.id, name: clients.name, contactEmail: clients.contactEmail })
      .from(clients)
      .where(eq(clients.isActive, true));

    for (const client of activeClients) {
      const recipientEmail = tenant.autoReportEmail ?? client.contactEmail;
      if (!recipientEmail) continue;

      const [report] = await db.insert(reports).values({
        tenantId: tenant.id,
        clientId: client.id,
        year,
        month: prevMonth,
        title: `Raport SEO ${client.name} ${prevMonth}/${year}`,
        status: "generating",
        recipientEmail,
        templateType: "full",
        isAutoGenerated: true,
      }).returning();

      await scheduleReportGeneration(report.id);
    }

    console.log(`[auto-reports] Scheduled ${activeClients.length} reports for ${prevMonth}/${year}`);
  } catch (err) {
    console.error("[auto-reports] Error:", err);
  }
}

// Sprawdzaj codziennie o 6:00
function scheduleDaily() {
  const now = new Date();
  const next6am = new Date(now);
  next6am.setHours(6, 0, 0, 0);
  if (next6am <= now) next6am.setDate(next6am.getDate() + 1);
  const ms = next6am.getTime() - now.getTime();
  setTimeout(() => {
    generateMonthlyReports();
    setInterval(generateMonthlyReports, 24 * 60 * 60 * 1_000);
  }, ms);
}

scheduleDaily();
